Model Training - Using Random Forest for a Classification problem

In [23]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [24]:
df = pd.read_csv("../data/synthetic_metrics.csv")
df

,resource_id,cpu_avg,cpu_p95,memory_avg,network_pct,internet_facing,identity_attached,cpu_spike_ratio,resource_saturation,load_efficiency,anomaly_type,is_anomalous
0,i-0522,83.4,96.8,56.1,63.9,True,True,1.162,69.722,0.758,cpu_saturated,True
1,i-0738,22.5,40.1,90.4,29.1,True,False,1.780,56.470,1.238,memory_pressure,True
2,i-0741,27.0,41.6,96.7,24.1,False,False,1.540,61.864,0.861,memory_pressure,True
3,i-0661,29.9,44.6,97.0,21.7,False,False,1.495,63.415,0.703,memory_pressure,True
4,i-0412,87.7,96.5,54.6,62.2,False,True,1.100,71.180,0.701,cpu_saturated,True
...,...,...,...,...,...,...,...,...,...,...,...,...
995,i-0107,35.5,53.8,53.4,47.3,True,False,1.516,44.427,1.297,normal,False
996,i-0271,1.7,6.7,37.3,10.2,False,False,3.891,19.523,3.735,over_provisioned,True
997,i-0861,69.5,78.9,44.4,11.6,False,True,1.137,56.932,0.165,traffic_cpu_mismatch,True
998,i-0436,90.1,97.2,62.1,69.7,True,True,1.079,76.075,0.765,cpu_saturated,True
999,i-0103,20.7,37.2,36.9,42.5,False,False,1.794,28.819,1.957,normal,False

In [25]:
df.describe()

,cpu_avg,cpu_p95,memory_avg,network_pct,cpu_spike_ratio,resource_saturation,load_efficiency
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,41.965200,53.528200,53.327300,41.732600,1.737856,47.645193,3.146467
std,31.799678,32.738698,18.820326,24.362201,1.208939,19.907196,6.917188
min,1.000000,2.000000,19.400000,1.000000,1.000000,11.079000,0.012000
25%,11.875000,18.800000,39.800000,18.275000,1.137000,24.974500,0.717000
50%,33.100000,51.700000,50.350000,41.100000,1.474500,48.733500,1.063500
75%,80.350000,89.500000,59.900000,60.825000,1.686000,65.411000,1.674250
max,100.000000,100.000000,100.000000,97.000000,11.304000,82.307000,43.903000

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   resource_id          1000 non-null   str
 1   cpu_avg              1000 non-null   float64
 2   cpu_p95              1000 non-null   float64
 3   memory_avg           1000 non-null   float64
 4   network_pct          1000 non-null   float64
 5   internet_facing      1000 non-null   bool
 6   identity_attached    1000 non-null   bool
 7   cpu_spike_ratio      1000 non-null   float64
 8   resource_saturation  1000 non-null   float64
 9   load_efficiency      1000 non-null   float64
 10  anomaly_type         1000 non-null   str
 11  is_anomalous         1000 non-null   bool
dtypes: bool(3), float64(7), str(2)
memory usage: 73.4 KB

In [40]:
null_check = df.isna().value_counts()
null_check

resource_id  cpu_avg  cpu_p95  memory_avg  network_pct  internet_facing  identity_attached  cpu_spike_ratio  resource_saturation  load_efficiency  anomaly_type  is_anomalous
False        False    False    False       False        False            False              False            False                False            False         False           1000
Name: count, dtype: int64